openapi: 3.0.0
info:
  title: Sample API
  description: Demo API
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: API endpoint
paths:
  /dogs:
    get:
      summary: Returns a list of Dogs
      responses:
        '200':
          description: A JSON array of Dogs
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Dog'
              example:
                [
                  {
                    "id": "123721397293abc",
                    "name": "Dog 1"
                  },
                  {
                    "id": "123721397293abd",
                    "name": "Dog 2"
                  }
                ]

components:
  schemas:
    Dog:
      type: object
      properties:
        id:
          type: integer
          description: Dog Id
        name:
          type: string
          description: Dog Name